config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  get '/about', to: 'about#index'

  resources :products, only: [:index, :show] do
    root to: 'reviews#create'
    resources :reviews, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  has_many :reviews
  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  http_basic_authenticate_with name: ENV['username'], password: ENV['password']

  def index
    @products = Product.order(id: :desc).all
    @prices = []
    @products.each {|item| @prices.push(item.price)}
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
require "action_view"
include ActionView::Helpers::NumberHelper

class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
    @price = number_to_currency(@product.price, options = { delimiter: ","} )
    @reviews = Review.where(product_id: @product.id).order(created_at: :desc)
    @review = Review.new
  end

end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_product.html.erb
<style>
  .sold_out {
    background: red;
    color: white;
    opacity: 0.5;
    font-size: 12px;
    font-weight: 700;
    padding: 6px 12px;
    position: absolute;
    left: ;
    top: 0;
    border-bottom-right-radius: 10px;
  }
</style>

<article>
  <% if product.quantity == 0 %>
  <span class="sold_out">SOLD OUT</span>
  <% end %>

  <%= link_to product_path(product) do %>
    <%= image_tag product.image.thumb.url , alt: product.name %>
    <h1>
      <span><%= product.name %></span>
      <span><%= humanized_money_with_symbol product.price %></span>
    </h1>
  <% end %>
  <div>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn' ,
    method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %> 
    <% end %>
  </div>
</article>

app/views/products/_review.html.erb
<% if @reviews.count > 0 %>
  <thead>
    <tr>
      <th>User</th>
      <th>Rating</th>
      <th>Review</th>
      <% @product.reviews.reverse.each do |review| %>
        <% if verifyUser?(review.user.id, current_user.id) %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td class="center"><%= review.user.first_name %></td>
      <td class="<%= getStars(review.rating) %> yellow center"></td>
      <td><%= review.description %></td>
      <% if verifyUser?(review.user.id, current_user.id) %>
        <td>
          <%= link_to fa_icon('trash'),
            product_review_path(@product.id, review),
            class: 'btn btn-sm btn-danger', method: :delete
          %>
        </td>
      <% end %>
    </tr>
  </tbody>
<% else %>
  <div class="text-center no-reviews">
    <p>No customer reviews yet.</p>
  </div
<% end %>

app/views/products/_review_form.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <%= form_for [@product, @review] do |form| %>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control', cols: "20", rows: "5" %>
      </div>

      <div class="form-group">
        <%= form.label :rating %>
        <%= form.select :rating, [1, 2, 3, 4, 5], include_blank: true, class: 'form-control' %>
      </div>

      <%= form.submit 'Create Review', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<section class="products-index">
  <header class="page-header">
    <div class="intro">
      <p>
        Looking for a way to add some life to your home? Look no further than our online plant shop! We have a wide variety of beautiful plants and flowers, as well as all the accessories you need to keep them healthy and happy. Plus, our prices are unbeatable! So what are you waiting for?
      </p>
      <p>
        At our online plant shop, we only sell the highest quality plants and flowers. We source our products from reputable growers and nurseries, so you can be sure you're getting a healthy, beautiful plant. Plus, ordering is quick and easy! We offer free shipping on all orders over $50, so it's easy to get the plants you want without breaking the bank.
      </p>
      <p>
        We have a wide variety of plants and flowers available for purchase on our website. Whether you're looking for something small and delicate or big and bold, we have the perfect plant for you. We also carry a selection of accessories, including potting soil, pots and containers, watering cans, and more.
      </p>
    </div>
  </header>

  <div class="products">
    <%= render @products %>
  </div>
</section>

app/views/products/show.html.erb
<section class="products-show">
  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">
    <%= image_tag @product.image.url, class: 'main-img' %>
    <div>
      <h1><%= @product.name %></h1>
      <p><%= @product.description %></p>
      <div class="quantity">
        <% if @product.quantity == 0 %>
          <span> SOLD OUT </span>
        <% else %>
          <span><%= @product.quantity %> in stock at </span>
        <% end %>
        <span><%= humanized_money_with_symbol @product.price %></span>
      </div>
      <div class="price">
        <% if @product.quantity > 0 %>
          <%= button_to add_item_cart_path(product_id: @product.id), class: 'btn' , method: :post do %>
            <%= fa_icon "shopping-cart", text: 'Add' %>
          <% end %>
        <% end %>          
      </div>
    </div>
  </article>
  
  <% if current_user %>
    <%= render "review_form" %>
  <% end %>

  <table class="table table-bordered"><br>
    <%= render "review" %>
  </table>

</section>